import Reveal from "../components/ui/Reveal";
import SectionHeader from "../components/ui/SectionHeader";

/**
 * About + methodology summary page. Structure adopted from the CASA reference
 * EV project: hero éˆ«?3-part section cards éˆ«?team éˆ«?methodology essay éˆ«?data
 * sources table éˆ«?tech stack chips. The detailed mathematical methodology
 * lives on the Methodology route; this page is the "story-of-the-project"
 * companion that addresses the rubric's contributions / AI / open-data
 * requirements directly.
 */

const PARTS = [
  {
    number: "01",
    title: "Story",
    summary:
      "An editorial scrollytelling sequence that introduces baseline accessibility (PTAL), the disruption hypothesis, and the resulting fallback-mobility map.",
    accent: "cool" as const,
  },
  {
    number: "02",
    title: "Explorer",
    summary:
      "An interactive scenario explorer for switching disruption line and metric, ranking neighbourhoods, comparing scenarios side-by-side, and inspecting a five-dimension fallback profile.",
    accent: "accent" as const,
  },
  {
    number: "03",
    title: "Methodology",
    summary:
      "Full indicator definitions (LTIS, retention, loss, dependency, exposure, Gini), references, limitations and open-data declarations.",
    accent: "warm" as const,
  },
];

const TEAM = [
  {
    name: "Yuxiang Fan",
    initials: "YF",
    role: "Frontend, design system, scrollytelling, deployment",
  },
  {
    name: "Siyan Tao",
    initials: "ST",
    role: "Data pipeline, methodology writing, references",
  },
];

const SOURCES = [
  {
    part: "Baseline",
    name: "PTAL 2023 (LSOA aggregated)",
    description:
      "TfL's Public Transport Accessibility Level grid aggregated to 2021 LSOAs (mean accessibility index + dominant PTAL band). Provides the baseline LTIS denominator.",
  },
  {
    part: "Geometry",
    name: "ONS LSOA 2021 boundaries",
    description:
      "4,994 Lower Super Output Areas across Greater London. Used as the spatial unit throughout the project.",
  },
  {
    part: "Network",
    name: "Underground Stations (TfL)",
    description:
      "273 station points with line-membership metadata (LINES). Drives the line-disruption scenario logic and the tube-line overlay on the map.",
  },
  {
    part: "Network",
    name: "Tube line geometry",
    description:
      "Line geometry approximated by chaining each line's stations west-to-east with a nearest-neighbour walk; used as a visual scaffold, not as a routing layer.",
  },
  {
    part: "Context",
    name: "OpenStreetMap + CARTO Positron",
    description:
      "Light raster basemap. æ¼ OpenStreetMap contributors æ¼ CARTO. Provides editorial map context without overwhelming the choropleth.",
  },
  {
    part: "Reference",
    name: "Resilience literature",
    description:
      "Bruneau (2003), Cats (2016), Chopra (2016), Cox (2011), Derrible (2010), D'Lima (2016), Henry (2012), Jenelius (2010), Sharma (2024). Full citations on the methodology page.",
  },
];

const TECH = [
  "React 19",
  "TypeScript",
  "Vite",
  "MapLibre GL",
  "d3-geo",
  "d3-shape",
  "scrollama",
  "KaTeX",
  "Python è·¯ Shapely",
  "GitHub Actions",
];

const AI_USAGE = [
  {
    tool: "Anthropic Claude (via Claude Code)",
    purpose:
      "Code scaffolding, MapLibre layer wiring, React component structure, ADR drafting, and PTALéˆ«æ‰¡TIS conversion script. Every artefact was inspected and edited by a named author before being committed.",
  },
  {
    tool: "OpenAI ChatGPT",
    purpose:
      "Licence-term disambiguation and copy-editing of the methodology summary. No analytical findings, methodological choices, citations or final wording were generated by an AI tool without author review.",
  },
];

export default function AboutRoute() {
  return (
    <article className="about-page">
      {/* éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬ Hero éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬ */}
      <Reveal>
        <header className="about-hero">
          <p className="eyebrow">About this project</p>
          <h1>London Transit Immune System</h1>
          <p className="about-hero__lede">
            <em>LTIS</em> is a group data-visualisation project investigating
            how unevenly transport resilience is distributed across London
            neighbourhoods. Produced as part of the CASA0029 module at the
            Centre for Advanced Spatial Analysis, University College London,
            2025/26 (Group 17).
          </p>
        </header>
      </Reveal>

      {/* éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬ 3-part overview éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬ */}
      <section className="about-section">
        <SectionHeader
          eyebrow="Site structure"
          title="Three connected views of the same question"
          description="The site moves from narrative to dashboard to method, with each part building on the previous one."
        />
        <div className="about-parts-grid">
          {PARTS.map((p, i) => (
            <Reveal key={p.number} delay={i * 0.08}>
              <article className={`about-part-card about-part-card--${p.accent}`}>
                <p className="about-part-number">{p.number}</p>
                <h3>{p.title}</h3>
                <p>{p.summary}</p>
              </article>
            </Reveal>
          ))}
        </div>
      </section>

      {/* éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬ Team éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬ */}
      <section className="about-section">
        <SectionHeader
          eyebrow="Contributors"
          title="Team"
          description="A two-person group with clearly separated technical responsibilities."
        />
        <div className="about-team-grid">
          {TEAM.map((m) => (
            <div key={m.name} className="about-team-card">
              <div className="about-team-avatar">{m.initials}</div>
              <div>
                <p className="about-team-card__name">{m.name}</p>
                <p className="about-team-card__role">{m.role}</p>
              </div>
            </div>
          ))}
        </div>
        <p className="muted" style={{ fontSize: "var(--text-sm)", maxWidth: "60ch" }}>
          The full Contributions Table éˆ¥?task-by-task ownership across data
          collection, methodology, frontend, design, methodology writing, and
          deployment éˆ¥?is mirrored in <code>submission/Group17_Project_Info.md</code> for
          the PDF deliverable.
        </p>
      </section>

      {/* éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬ Methodology essay éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬ */}
      <section className="about-section">
        <SectionHeader
          eyebrow="About the work"
          title="How the project was built"
          description="Research framing, indicator construction, and transparency notes. The mathematical formulation, references and limitations live on the Methodology page."
        />
        <div className="prose" style={{ maxWidth: "var(--container-narrow)" }}>
          <h3>Research framing</h3>
          <p>
            LTIS asks a question that sits at the intersection of transport
            resilience research and spatial equity: when a single Underground
            line is disrupted, which neighbourhoods retain meaningful
            alternative mobility éˆ¥?and which become structurally exposed? The
            project is built around a single composite indicator (LTIS) whose
            sub-components are interpretable in isolation: <em>retention</em>,
            <em> loss</em>, <em>dependency</em> and <em>exposure</em>.
          </p>

          <h3>Baseline accessibility</h3>
          <p>
            We adopt PTAL 2023 (mean accessibility index + dominant PTAL band)
            aggregated to 2021 LSOAs as the baseline denominator. PTAL is a
            well-established TfL measure that captures walking distance to
            public transport stops weighted by service frequency; using it as
            the baseline grounds the project in a recognised London transport
            indicator rather than a bespoke composite.
          </p>

          <h3>Disruption scenarios</h3>
          <p>
            For each of three scenarios éˆ¥?Central, Northern and Jubilee line
            disruption éˆ¥?we compute, for every LSOA, a dependency share equal
            to the proportion of nearby Underground stations belonging to the
            disrupted line within an approximately 1.3 km walking catchment. A
            severity coefficient maps that dependency share into a loss
            fraction, from which retention, exposure and the five-dimension
            fallback profile are derived. The choice of severity (0.55) and
            catchment (~1.3 km) is documented as an ADR.
          </p>

          <h3>Spatial unit</h3>
          <p>
            All choropleth output is at the 2021 LSOA level (4,994 features
            across Greater London). LSOAs are the standard ONS spatial unit
            for neighbourhood-scale social analysis and align with the IMD,
            census and PTAL aggregation. Borough roll-ups are produced for
            headline summaries only; all interactive visualisations remain at
            LSOA scale.
          </p>

          <h3>Reproducibility &amp; open data</h3>
          <p>
            All code is MIT-licensed and version-controlled. The PTALéˆ«æ‰¡TIS
            pipeline lives in <code>analysis/build_ltis_from_ptal.py</code>; the
            input data, intermediate joins and output GeoJSON are all
            published in the repository with their provenance documented in
            <code> data/DATA_SOURCES.md</code>. Citation metadata is in
            <code> CITATION.cff</code> and key design decisions are recorded
            as ADRs in <code>docs/decisions/</code>.
          </p>

          <h3>Limitations &amp; transparency</h3>
          <p>
            Tube line geometry is an approximation chained from station
            points (no GTFS shapes are joined yet) and is used as a visual
            scaffold, not as a routing layer. The 1.3 km catchment is a
            deliberate simplification of multimodal accessibility éˆ¥?bus and
            rail fallback are handled separately as fallback-profile
            dimensions. PTAL itself is a frequency-weighted walking measure
            and inherits the limitations described in TfL's PTAL methodology
            note. The exposure metric uses a fixed per-LSOA population
            baseline; an upgraded version using the live ONS mid-year
            estimates is on the project roadmap.
          </p>
        </div>
      </section>

      {/* éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬ AI usage éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬ */}
      <section className="about-section">
        <SectionHeader
          eyebrow="Transparency"
          title="AI tool usage"
          description="Per CASA0029 marking guidance, every AI-assisted artefact is itemised below. Final author review applied to all outputs."
        />
        <div className="about-sources">
          <div className="about-sources-row about-sources-row--head">
            <span>Tool</span>
            <span>Purpose</span>
            <span>Review</span>
          </div>
          {AI_USAGE.map((u) => (
            <div className="about-sources-row" key={u.tool}>
              <strong>{u.tool}</strong>
              <span>{u.purpose}</span>
              <span>Author-reviewed before commit</span>
            </div>
          ))}
        </div>
      </section>

      {/* éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬ Data sources éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬ */}
      <section className="about-section">
        <SectionHeader
          eyebrow="Data"
          title="Data sources"
          description="All datasets used in this project are publicly available. Full citations live on the Methodology page."
        />
        <div className="about-sources">
          <div className="about-sources-row about-sources-row--head">
            <span>Layer</span>
            <span>Dataset</span>
            <span>Used for</span>
          </div>
          {SOURCES.map((s) => (
            <div className="about-sources-row" key={s.name}>
              <span>{s.part}</span>
              <strong>{s.name}</strong>
              <span>{s.description}</span>
            </div>
          ))}
        </div>
      </section>

      {/* éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬ Tech éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬éˆ¹â‚¬ */}
      <section className="about-section">
        <SectionHeader
          eyebrow="Stack"
          title="Tools &amp; technologies"
          description="The site is fully open-source and uses no proprietary visualisation libraries."
        />
        <div className="about-tag-strip">
          {TECH.map((t) => (
            <span key={t} className="about-tag">
              {t}
            </span>
          ))}
        </div>
      </section>
    </article>
  );
}
